title: "My Blog"
description: "A simple blog."
baseurl: "/blog"
url: "https://ro99.github.io"

plugins:
  - jekyll-seo-tag
  - jekyll-feed

markdown: kramdown
usemathjax: true

tikz:
  pdf2svg: "/usr/bin/pdf2svg"