title: "My Blog"
description: "A simple blog."
baseurl: "/blog"
url: "https://ro99.github.io"

include:
  - assets/images

plugins:
  - jekyll-seo-tag
  - jekyll-feed

markdown: kramdown
usemathjax: true

tikz:
  pdf2svg: "pdf2svg"
